import { useState } from 'react';
import { BasicAuthSelector, type BasicGroup } from './BasicAuth';
import { FileCode2, Loader2, Upload, Check, Settings2, Plus, Trash2 } from 'lucide-react';

export type ImportedBackend={name:string;mode:string;balance:string|null;servers:{name:string;address:string;port:number;weight:number;tls:boolean}[]};
export type ImportedRoute={id:string;frontend:string;domain:string;backend:string;basic_auth_group?:number|null;basic_auth_forward?:boolean};
export type ImportedFields={imported_config?:string|null;imported_backends?:ImportedBackend[];imported_routes?:ImportedRoute[];imported_route_frontends?:string[];imported_sources?:{path:string;hash:string}[]};
type Request=(path:string,method?:string,body?:unknown)=>Promise<any>;

export function ConfigImport({id,request,onDone}:{id:number;request:Request;onDone:(doc:any)=>void}){
  const [source,setSource]=useState('agent'),[config,setConfig]=useState(''),[extra,setExtra]=useState<{name:string;content:string}[]>([]),[maps,setMaps]=useState<{path:string;content:string}[]>([]);
  const [preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const payload=source==='agent'?{}:{config:config+'\n'+extra.map(f=>f.content).join('\n\n'),maps};
  async function load(){setBusy(true);setError('');try{setPreview(await request(`/instances/${id}/import-preview`,'POST',payload));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function commit(){setBusy(true);setError('');try{onDone(await request(`/instances/${id}/import`,'POST',{...payload,active_hash:preview.active_hash,document_version:preview.document_version,preview_hash:preview.preview_hash}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function readFiles(files:FileList|null,kind:'config'|'extra'|'maps'){
    if(!files)return;setError('');setPreview(null);
    try{
      if(Array.from(files).reduce((sum,f)=>sum+f.size,0)>1024*1024)throw new Error('Dateien zusammen höchstens 1 MB groß.');
      const data=await Promise.all(Array.from(files).map(async f=>({name:f.name,content:await f.text()})));
      if(kind==='config')setConfig(data[0]?.content||'');
      if(kind==='extra')setExtra(data.sort((a,b)=>a.name.localeCompare(b.name,'en')));
      if(kind==='maps')setMaps(data.map(f=>({path:'/etc/haproxy/maps/'+f.name,content:f.content})));
    }catch(e){setError((e as Error).message);}
  }
  return <div className="form-body">
    <div className="notice"><FileCode2 size={18}/><span>Importiert in einen grafischen Entwurf. HAProxy bleibt unverändert, bis du eine erzeugte Konfiguration prüfst und anwendest. Vorhandene Einstellungen werden erhalten. <a href="/api/import-guide">Import-Anleitung herunterladen</a></span></div>
    {error&&<div role="alert" className="notice error">{error}</div>}
    {!preview?<>
      <div className="field"><label htmlFor="import-source">Quelle</label><select id="import-source" value={source} onChange={e=>setSource(e.target.value)}><option value="agent">Aktive Dateien vom HAProxy-Agenten einlesen</option><option value="files">Konfiguration und Maps hochladen / einfügen</option></select></div>
      {source==='agent'?<p className="wizard-intro">Der Agent erkennt die geladenen -f-Dateien und Verzeichnisse sowie referenzierte Host-Maps. Dafür muss der Agent diese Funktion unterstützen. Unter Server findest du den Befehl zur Aktualisierung.</p>:<>
        <div className="field"><label htmlFor="import-main-file">Hauptkonfiguration (.cfg)</label><input id="import-main-file" type="file" accept=".cfg,.conf,.txt" onChange={e=>void readFiles(e.target.files,'config')}/></div>
        <textarea className="wizard-command" aria-label="Konfiguration für Import" rows={8} placeholder="global … defaults … frontend …" value={config} onChange={e=>setConfig(e.target.value)}/>
        <div className="field"><label htmlFor="import-extra-files">Weitere Konfigurationsdateien (.cfg, alphabetische Reihenfolge)</label><input id="import-extra-files" type="file" multiple accept=".cfg,.conf,.txt" onChange={e=>void readFiles(e.target.files,'extra')}/><small>{extra.map(f=>f.name).join(', ')}</small></div>
        <div className="field"><label htmlFor="import-map-files">Host-Maps (.map)</label><input id="import-map-files" type="file" multiple accept=".map,.txt" onChange={e=>void readFiles(e.target.files,'maps')}/></div>
        {maps.map((map,i)=><div className="field" key={i}><label htmlFor={'map-path-'+i}>Map-Pfad aus der HAProxy-Konfiguration</label><input id={'map-path-'+i} value={map.path} onChange={e=>setMaps(old=>old.map((m,j)=>i===j?{...m,path:e.target.value}:m))}/></div>)}
      </>}
      <div className="modal-actions"><button type="button" className="button" disabled={busy||source==='files'&&!config.trim()} onClick={()=>void load()}>{busy?<Loader2 size={16} className="spin"/>:<Upload size={16}/>}Einlesen & Vorschau</button></div>
    </>:<>
      <div className="proxy-summary"><div><strong>{preview.summary.frontends}</strong><span>Frontends</span></div><div><strong>{preview.summary.editable_backends}</strong><span>Bearbeitbare Pools</span></div><div><strong>{preview.summary.routes}</strong><span>Domain-Zuordnungen</span></div></div>
      <p className="wizard-intro">{preview.summary.editable_servers} Zielserver · {preview.summary.tcp} TCP-Abschnitte · {preview.summary.converted_maps} Host-Maps werden in explizite Domain-Routen überführt. Globale Einstellungen, Header, Authentifizierung und übrige Regeln bleiben im Konfigurationstext erhalten.</p>
      {preview.source_files?.length>1&&<div className="notice"><span>Beim späteren Anwenden werden {preview.source_files.length} geladene Dateien in der Hauptkonfiguration zusammengeführt. Die übrigen Dateien bleiben als Kommentar-Dateien vorhanden, damit dieselben Abschnitte nicht doppelt geladen werden. Alle Originaldateien werden auf dem Agenten gesichert.</span></div>}
      <div className="table-wrap"><table><thead><tr><th>ABSCHNITT</th><th>MODUS</th><th>ERKANNT ALS</th></tr></thead><tbody>{preview.proxies.map((p:any,i:number)=><tr key={i}><td><strong>{p.name}</strong><small>{p.kind}</small></td><td><span className="badge">{p.mode.toUpperCase()}</span></td><td>{p.service}</td></tr>)}</tbody></table></div>
      {preview.warnings.length>0&&<div className="notice"><div><strong>Hinweise zur Übernahme</strong><ul>{preview.warnings.map((w:string,i:number)=><li key={i}>{w}</li>)}</ul></div></div>}
      <div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setPreview(null)}>Zurück</button><button type="button" className="button" disabled={busy} onClick={()=>void commit()}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}Als grafischen Entwurf übernehmen</button></div>
    </>}
  </div>;
}

export function ImportedConfigPanel({groups,doc,onSave,onImport,onGenerate,busy}:{groups:BasicGroup[];doc:ImportedFields;onSave:(changes:ImportedFields)=>Promise<void>;onImport:()=>void;onGenerate:()=>void;busy:boolean}){
  const [backend,setBackend]=useState<ImportedBackend|null>(null),[route,setRoute]=useState<ImportedRoute|null>(null),[routeIndex,setRouteIndex]=useState<number|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const backends=doc.imported_backends||[],routes=doc.imported_routes||[];
  async function save(changes:ImportedFields){setSaving(true);setError('');try{await onSave(changes);setBackend(null);setRoute(null);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  const fronts=doc.imported_route_frontends||Array.from(new Set(routes.map(r=>r.frontend)));
  return <>
    <div className="draft-banner"><FileCode2 size={20}/><div><strong>Übernommene Konfiguration</strong><span>Domain-Routen und Backend-Ziele bearbeiten. Übrige Einstellungen bleiben im Text erhalten.</span></div><button className="button secondary" disabled={busy} onClick={onGenerate}>Konfiguration erzeugen</button><button className="text-button" disabled={busy} onClick={onImport}>Erneut einlesen</button></div>
    {error&&<div role="alert" className="notice error">{error}</div>}
    <section className="panel"><div className="panel-header"><div><h2>Übernommene Domain-Zuordnungen</h2><p>Host-Maps: Domain → Backend-Pool. Listener, Header und Redirects bleiben erhalten.</p></div>{fronts.length>0&&<button className="button" disabled={busy} onClick={()=>{setRouteIndex(null);setRoute({id:'route_'+(crypto.randomUUID?crypto.randomUUID().replaceAll('-','').slice(0,16):Math.random().toString(36).slice(2)),frontend:fronts[0],domain:'',backend:backends[0]?.name||''});}}><Plus size={16}/>Domain</button>}</div>
      {routes.length?<div className="table-wrap"><table><thead><tr><th>DOMAIN</th><th>FRONTEND</th><th>BACKEND</th><th></th></tr></thead><tbody>{routes.map((r,i)=><tr key={r.id}><td><strong>{r.domain}</strong></td><td>{r.frontend}</td><td>{r.backend}{r.basic_auth_group&&<small>Basic Auth · {groups.find(g=>g.id===r.basic_auth_group)?.name||"Gruppe #"+r.basic_auth_group}</small>}</td><td><button className="icon-button" aria-label={'Domain '+r.domain+' bearbeiten'} onClick={()=>{setRouteIndex(i);setRoute({...r});}}><Settings2 size={16}/></button><button className="icon-button red-text" aria-label={'Domain '+r.domain+' entfernen'} disabled={busy} onClick={()=>void save({imported_routes:routes.filter((_,j)=>j!==i)})}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>:<p className="stats-empty">Keine einfachen Host-Map-Routen erkannt. Bestehende ACLs und dynamische Regeln bleiben im Texteditor erhalten.</p>}
    </section>
    <section className="panel"><div className="panel-header"><div><h2>Übernommene Backend-Pools</h2><p>HTTP und TCP getrennt gekennzeichnet. Healthchecks und zusätzliche Serveroptionen bleiben erhalten.</p></div><span className="badge">{backends.length}</span></div><div className="table-wrap"><table><thead><tr><th>POOL</th><th>MODUS</th><th>ZIELSERVER</th><th>VERTEILUNG</th><th></th></tr></thead><tbody>{backends.map(b=><tr key={b.name}><td><strong>{b.name}</strong></td><td><span className={'badge '+(b.mode==='tcp'?'amber':'neutral')}>{b.mode.toUpperCase()}</span></td><td>{b.servers.map(s=><small key={s.name} className="mono">{s.name} · {s.address}:{s.port}{s.tls?' · TLS':''}</small>)}</td><td>{b.balance||'Eigener Algorithmus'}</td><td><button className="icon-button" aria-label={'Backend '+b.name+' bearbeiten'} onClick={()=>setBackend(structuredClone(b))}><Settings2 size={16}/></button></td></tr>)}</tbody></table></div></section>
    {backend&&<section className="panel imported-edit"><h3>Backend {backend.name} bearbeiten</h3><form onSubmit={e=>{e.preventDefault();void save({imported_backends:backends.map(b=>b.name===backend.name?backend:b)});}}><div className="field"><label htmlFor="imported-balance">Verteilung</label><select id="imported-balance" value={backend.balance||''} onChange={e=>setBackend({...backend,balance:e.target.value||null})}>{!backend.balance&&<option value="">Vorhandenen Algorithmus behalten</option>}<option value="roundrobin">Round Robin</option><option value="leastconn">Least Connections</option><option value="source">Source</option></select></div>{backend.servers.map((s,i)=><div className="form-grid imported-server-edit" key={s.name}><strong>{s.name}{s.tls?' · TLS':''}</strong>{(['address','port','weight'] as const).map(key=><div className="field" key={key}><label htmlFor={`import-${i}-${key}`}>{key==='address'?'Zieladresse':key==='port'?'Port':'Gewicht'}</label><input id={`import-${i}-${key}`} required type={key==='address'?'text':'number'} min={key==='port'?1:0} max={key==='port'?65535:256} value={s[key]} onChange={e=>setBackend({...backend,servers:backend.servers.map((sv,j)=>i===j?{...sv,[key]:key==='address'?e.target.value:Number(e.target.value)}:sv)})}/></div>)}</div>)}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setBackend(null)}>Abbrechen</button><button type="submit" className="button" disabled={saving}>Im Entwurf speichern</button></div></form></section>}
    {route&&<section className="panel imported-edit"><h3>Domain-Zuordnung bearbeiten</h3><form onSubmit={e=>{e.preventDefault();void save({imported_routes:routeIndex===null?[...routes,route]:routes.map((r,i)=>i===routeIndex?route:r)});}}><div className="field"><label htmlFor="imported-domain">Domain</label><input id="imported-domain" required value={route.domain} onChange={e=>setRoute({...route,domain:e.target.value})}/></div><div className="form-grid"><div className="field"><label htmlFor="imported-frontend">Frontend</label><select id="imported-frontend" value={route.frontend} onChange={e=>setRoute({...route,frontend:e.target.value})}>{fronts.map(f=><option key={f}>{f}</option>)}</select></div><div className="field"><label htmlFor="imported-target">Backend-Pool</label><input id="imported-target" required list="imported-backend-options" value={route.backend} onChange={e=>setRoute({...route,backend:e.target.value})}/><datalist id="imported-backend-options">{backends.map(b=><option key={b.name} value={b.name}/>)}</datalist></div></div><BasicAuthSelector groups={groups} value={route.basic_auth_group} forward={route.basic_auth_forward} disabled={backends.find(b=>b.name===route.backend)?.mode==='tcp'} onChange={id=>setRoute({...route,basic_auth_group:id,basic_auth_forward:false})} onForward={forward=>setRoute({...route,basic_auth_forward:forward})}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setRoute(null)}>Abbrechen</button><button type="submit" className="button" disabled={saving}>Im Entwurf speichern</button></div></form></section>}
    <p className="stats-note">Neue TCP-Listener, komplexe ACLs, eigene Authentifizierungsregeln und TLS-Parameter werden weiterhin im vollständigen Konfigurationseditor bearbeitet. Zentrale Basic-Auth-Gruppen wählst du bei der Domain-Zuordnung. Änderungen werden erst nach Prüfung und Anwenden wirksam.</p>
  </>;
}
