import {useState} from 'react';
import {ArrowRight,Check,FileCode2,Globe2,Plus,Settings2,Trash2} from 'lucide-react';
import type {Certificate} from './Certificates';

export type Pool={name:string;mode:'http'|'tcp';balance:string;servers:{address:string;port:number;weight:number;tls:boolean}[]};
export type Frontend={name:string;mode:'http'|'tcp';bind_address:string;port:number;tls_enabled:boolean;backend:string|null};
export type LayoutProxy={name:string;kind:string;mode:string;service:string;binds:string[];routes:{backend:string;default:boolean}[];domains:string[];tls:boolean;targets?:{name:string;address:string;port:number}[]};
export type Layout={frontends:LayoutProxy[];backends:LayoutProxy[];error?:string|null};

export function ProxyLayout({layout,busy,canEdit,onFrontend,onBackend,onEditFrontend,onCertificates,onEditBackend,onRemoveFrontend,onRemoveBackend,removableFrontends,removableBackends,onGenerate,onHosts}:{layout:Layout|null;busy:boolean;canEdit:boolean;onFrontend:()=>void;onBackend:()=>void;onEditFrontend:(name:string)=>void;onCertificates:(name:string)=>void;onEditBackend:(name:string)=>void;onRemoveFrontend:(name:string)=>void;onRemoveBackend:(name:string)=>void;removableFrontends:string[];removableBackends:string[];onGenerate:()=>void;onHosts:()=>void}){
  return <><div className="draft-banner"><FileCode2 size={20}/><div><strong>Frontends empfangen · Backends verteilen</strong><span>HTTP-Reverseproxys verbinden Domains mit Zielen. TCP-Dienste verbinden einen Listener direkt mit einem Backend-Pool.</span></div>{canEdit&&<button className="button secondary" disabled={busy} onClick={onGenerate}>Konfiguration erzeugen</button>}</div>
  {layout?.error&&<div className="notice error">Entwurf noch unvollständig: {layout.error}</div>}
  <div className="notice"><Globe2 size={18}/><span>Ein neuer Proxy Host erzeugt seinen Backend-Pool automatisch und nutzt das gewählte HTTP-Frontend. <button className="text-button" disabled={busy} onClick={onHosts}>Proxy Hosts öffnen <ArrowRight size={14}/></button></span></div>
  <section className="panel"><div className="panel-header"><div><h2>Frontends / Listener</h2><p>Eingehende Ports, HTTP oder TCP, TLS-Zertifikate und Weiterleitung.</p></div>{canEdit&&<button className="button" disabled={busy} onClick={onFrontend}><Plus size={16}/>Frontend</button>}</div><div className="table-wrap"><table><thead><tr><th>FRONTEND</th><th>MODUS</th><th>LAUSCHT AUF</th><th>WEITERLEITUNG</th><th></th></tr></thead><tbody>{layout?.frontends.map(f=><tr key={f.name}><td><strong>{f.name}</strong><small>{f.service}</small></td><td><span className={'badge '+(f.mode==='tcp'?'amber':'blue')}>{f.mode.toUpperCase()}{f.tls?' · TLS':''}</span></td><td>{f.binds.map(b=><small className="mono" key={b}>{b}</small>)}</td><td>{f.routes.length?<details className="backend-targets"><summary>{f.routes.length} Zuordnungen</summary>{f.routes.map((r,i)=><small className="mono" key={i}>{r.backend}{r.default?' · Standard':''}</small>)}</details>:<small>Direkte Antwort / keine Route</small>}</td><td>{canEdit&&<div className="row-actions">{f.tls&&<button className="text-button" disabled={busy} onClick={()=>onCertificates(f.name)}>Zertifikate</button>}<button className="icon-button" disabled={busy} aria-label={'Frontend '+f.name+' bearbeiten'} onClick={()=>onEditFrontend(f.name)}><Settings2 size={16}/></button>{removableFrontends.includes(f.name)&&<button className="icon-button red-text" disabled={busy} aria-label={'Frontend '+f.name+' entfernen'} onClick={()=>onRemoveFrontend(f.name)}><Trash2 size={16}/></button>}</div>}</td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panel-header"><div><h2>Backends / Pools</h2><p>Zielserver und Lastverteilung, getrennt nach HTTP und TCP.</p></div>{canEdit&&<button className="button" disabled={busy} onClick={onBackend}><Plus size={16}/>Backend</button>}</div><div className="table-wrap"><table><thead><tr><th>BACKEND</th><th>MODUS</th><th>ZIELSERVER</th><th>VERBUNDENE FRONTENDS</th><th></th></tr></thead><tbody>{layout?.backends.map(b=><tr key={b.name}><td><strong>{b.name}</strong><small>{b.service}</small></td><td><span className={'badge '+(b.mode==='tcp'?'amber':'blue')}>{b.mode.toUpperCase()}</span></td><td>{b.targets?.length?<details className="backend-targets"><summary>{b.targets.length} Zielserver</summary>{b.targets.map(s=><small className="mono" key={s.name}>{s.name} · {s.address}:{s.port}</small>)}</details>:'Keine statischen Ziele'}</td><td>{layout.frontends.filter(f=>f.routes.some(r=>r.backend===b.name)).map(f=><small key={f.name} className="mono">{f.name}</small>)}</td><td>{canEdit&&<div className="row-actions"><button className="icon-button" disabled={busy} aria-label={'Backend-Pool '+b.name+' bearbeiten'} onClick={()=>onEditBackend(b.name)}><Settings2 size={16}/></button>{removableBackends.includes(b.name)&&<button className="icon-button red-text" disabled={busy} aria-label={'Backend-Pool '+b.name+' entfernen'} onClick={()=>onRemoveBackend(b.name)}><Trash2 size={16}/></button>}</div>}</td></tr>)}</tbody></table></div></section><p className="stats-note">Die Übersicht zeigt den Arbeitsentwurf. Änderungen werden nach Erzeugen, Prüfen und Anwenden aktiv. Übernommene Listener behalten ihre bisherigen Optionen; ihre TLS-Zertifikate lassen sich hier gezielt zuweisen.</p></>;
}

export function FrontendForm({initial,backends,busy,onClose,onSave}:{initial:Frontend|null;backends:LayoutProxy[];busy:boolean;onClose:()=>void;onSave:(v:Frontend)=>Promise<void>}){
  const [v,setV]=useState<Frontend>(initial||{name:'',mode:'tcp',bind_address:'0.0.0.0',port:3306,tls_enabled:false,backend:null}),[error,setError]=useState('');
  return <form className="form-body" onSubmit={async e=>{e.preventDefault();setError('');try{await onSave(v);}catch(e){setError((e as Error).message);}}}><fieldset disabled={busy} className="imported-form-fields">{error&&<div className="notice error" role="alert">{error}</div>}<div className="form-grid"><div className="field"><label htmlFor="frontend-name">Frontend-Name</label><input id="frontend-name" required readOnly={!!initial} pattern="[a-zA-Z0-9_.-]+" maxLength={100} value={v.name} onChange={e=>setV({...v,name:e.target.value})} placeholder="fe_mysql"/></div><div className="field"><label htmlFor="frontend-mode">Modus</label><select id="frontend-mode" value={v.mode} onChange={e=>setV({...v,mode:e.target.value as Frontend['mode'],backend:null})}><option value="http">HTTP / Reverseproxy</option><option value="tcp">TCP / TLS-Passthrough</option></select></div></div><div className="form-grid"><div className="field"><label htmlFor="frontend-address">Bind-IP</label><input id="frontend-address" required value={v.bind_address} onChange={e=>setV({...v,bind_address:e.target.value})}/><small>0.0.0.0 für alle IPv4-Adressen; :: für IPv6.</small></div><div className="field"><label htmlFor="frontend-port">Port</label><input id="frontend-port" required type="number" min={1} max={65535} value={v.port} onChange={e=>setV({...v,port:Number(e.target.value)})}/></div></div><div className="field"><label htmlFor="frontend-backend">Standard-Backend</label><select id="frontend-backend" required={v.mode==='tcp'} value={v.backend||''} onChange={e=>setV({...v,backend:e.target.value||null})}><option value="">{v.mode==='tcp'?'Backend-Pool auswählen':'Domain-Routen über Proxy Hosts verwenden'}</option>{backends.filter(b=>b.mode===v.mode).map(b=><option key={b.name} value={b.name}>{b.name}</option>)}</select></div><label className="checkbox"><input type="checkbox" checked={v.tls_enabled} onChange={e=>setV({...v,tls_enabled:e.target.checked})}/>TLS hier beenden (gültiges Zertifikat erforderlich)</label><p className="stats-note">Bei TLS-Passthrough bleibt diese Option aus. Nach Anlegen eines TLS-Frontends kannst du dessen Zertifikate in der Übersicht auswählen. Docker-Ports müssen zusätzlich auf dem Host veröffentlicht sein.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Abbrechen</button><button type="submit" className="button"><Check size={16}/>Im Entwurf speichern</button></div></fieldset></form>;
}

export function BackendForm({initial,busy,onClose,onSave}:{initial:Pool|null;busy:boolean;onClose:()=>void;onSave:(v:Pool)=>Promise<void>}){
  const [v,setV]=useState<Pool>(initial?structuredClone(initial):{name:'',mode:'tcp',balance:'roundrobin',servers:[{address:'',port:3306,weight:100,tls:false}]}),[error,setError]=useState('');
  return <form className="form-body" onSubmit={async e=>{e.preventDefault();setError('');try{await onSave(v);}catch(e){setError((e as Error).message);}}}><fieldset disabled={busy} className="imported-form-fields">{error&&<div className="notice error" role="alert">{error}</div>}<div className="form-grid"><div className="field"><label htmlFor="pool-name">Backend-Name</label><input id="pool-name" required readOnly={!!initial} pattern="[a-zA-Z0-9_.-]+" maxLength={100} value={v.name} onChange={e=>setV({...v,name:e.target.value})} placeholder="be_mysql"/></div><div className="field"><label htmlFor="pool-mode">Modus</label><select id="pool-mode" value={v.mode} onChange={e=>setV({...v,mode:e.target.value as Pool['mode']})}><option value="http">HTTP</option><option value="tcp">TCP</option></select></div></div><div className="field"><label htmlFor="pool-balance">Lastverteilung</label><select id="pool-balance" value={v.balance} onChange={e=>setV({...v,balance:e.target.value})}><option value="roundrobin">Round Robin</option><option value="leastconn">Wenigste Verbindungen</option><option value="source">Quell-IP</option></select></div>{v.servers.map((s,i)=><div className="backend-form" key={i}><div className="field"><label htmlFor={'pool-address-'+i}>Zieladresse</label><input id={'pool-address-'+i} required value={s.address} onChange={e=>setV({...v,servers:v.servers.map((x,j)=>j===i?{...x,address:e.target.value}:x)})}/></div><div className="field"><label htmlFor={'pool-port-'+i}>Port</label><input id={'pool-port-'+i} required type="number" min={1} max={65535} value={s.port} onChange={e=>setV({...v,servers:v.servers.map((x,j)=>j===i?{...x,port:Number(e.target.value)}:x)})}/></div><div className="field"><label htmlFor={'pool-weight-'+i}>Gewicht</label><input id={'pool-weight-'+i} required type="number" min={1} max={256} value={s.weight} onChange={e=>setV({...v,servers:v.servers.map((x,j)=>j===i?{...x,weight:Number(e.target.value)}:x)})}/></div><label className="checkbox"><input type="checkbox" checked={s.tls} onChange={e=>setV({...v,servers:v.servers.map((x,j)=>j===i?{...x,tls:e.target.checked}:x)})}/>Ziel-TLS</label><button type="button" className="icon-button red-text" disabled={v.servers.length===1} aria-label={'Zielserver '+(i+1)+' entfernen'} onClick={()=>setV({...v,servers:v.servers.filter((_,j)=>j!==i)})}><Trash2 size={16}/></button></div>)}<button type="button" className="text-button" onClick={()=>setV({...v,servers:[...v.servers,{address:'',port:v.mode==='tcp'?3306:80,weight:100,tls:false}]})}><Plus size={16}/>Zielserver hinzufügen</button><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Abbrechen</button><button type="submit" className="button"><Check size={16}/>Im Entwurf speichern</button></div></fieldset></form>;
}

export function FrontendCertificateForm({name,initial,certs,busy,onClose,onSave}:{name:string;initial:string[];certs:Certificate[];busy:boolean;onClose:()=>void;onSave:(names:string[])=>Promise<void>}){
  const [values,setValues]=useState(initial),[error,setError]=useState('');
  return <form className="form-body" onSubmit={async e=>{e.preventDefault();setError('');try{await onSave(values);}catch(e){setError((e as Error).message);}}}><fieldset disabled={busy} className="imported-form-fields">{error&&<div className="notice error" role="alert">{error}</div>}<p>Zertifikate für <strong>{name}</strong>. HAProxy wählt anhand des angefragten Domainnamens (SNI).</p>{certs.filter(c=>!c.staging&&!c.error).map(c=><label className="checkbox" key={c.name}><input type="checkbox" checked={values.includes(c.name)} onChange={e=>setValues(e.target.checked?[...values,c.name]:values.filter(v=>v!==c.name))}/><span>{c.name}<small>{c.domains?.join(', ')}</small></span></label>)}<p className="stats-note">Ohne explizite Auswahl bleibt die bisherige Bind-Zuweisung erhalten. Zertifikate aus einzelnen Proxy Hosts werden zusätzlich geladen. Eigene crt-list-Definitionen bearbeitest du im Konfigurationseditor.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Abbrechen</button><button type="submit" className="button"><Check size={16}/>Zuweisung speichern</button></div></fieldset></form>;
}
