import React, { useId, useState } from 'react';
import { ArrowRight, Download, MapPin, Search, Server, Settings2, Tags, Trash2, X } from 'lucide-react';

import { InfrastructureSelect, type Infrastructure } from './Infrastructures';

export type ServerClassification={tags:string[];location:string;metadata_version?:number;infrastructure_id?:number|null;infrastructure_name?:string|null};
type DirectoryServer=ServerClassification&{id:number;name:string;agent_url:string;profile:string;kind:string;notes:string;stats:{sessions?:number;request_rate?:number}|null};
const fmt=(value?:number)=>value==null?'—':new Intl.NumberFormat('de-DE').format(value);

export function ClassificationFields({value,onChange,infrastructures=[]}:{value:ServerClassification;onChange:(value:ServerClassification)=>void;infrastructures?:Infrastructure[]}){
  const id=useId(),[text,setText]=useState(value.tags.join(', '));
  return <div className="classification-fields"><InfrastructureSelect value={value.infrastructure_id??null} items={infrastructures} onChange={id=>onChange({...value,infrastructure_id:id})}/><div className="field"><label htmlFor={id+'-tags'}>Tags</label><input id={id+'-tags'} maxLength={1200} placeholder="z. B. Prod, Kunde A, Edge" value={text} onChange={e=>{setText(e.target.value);onChange({...value,tags:e.target.value.split(',').map(t=>t.trim()).filter(Boolean)});}}/><small>Mit Komma trennen. Bis zu 20 Tags mit je 40 Zeichen, z. B. Prod, Dev oder Staging.</small></div><div className="field"><label htmlFor={id+'-location'}>Standort</label><input id={id+'-location'} maxLength={120} placeholder="z. B. Frankfurt · Rechenzentrum 1" value={value.location} onChange={e=>onChange({...value,location:e.target.value})}/><small>Optional: Stadt, Rechenzentrum oder eigener Standortname.</small></div></div>;
}

export function ClassificationBadges({tags,location,infrastructure_name}:{tags:string[];location:string;infrastructure_name?:string|null}){
  return <>{infrastructure_name&&<span className="badge infrastructure-badge">{infrastructure_name}</span>}{location&&<span className="server-location"><MapPin size={14}/>{location}</span>}{tags.length>0&&<div className="classification-tags">{tags.map(tag=><span className="badge classification-tag" data-tag={tag.toLowerCase()} key={tag}><Tags size={11}/>{tag}</span>)}</div>}</>;
}

export function ServerDirectory({servers,isAdmin,busy,status,onManage,onEdit,onMetadata,onUpdate,onRemove}:{servers:DirectoryServer[];isAdmin:boolean;busy:boolean;status:(server:DirectoryServer)=>React.ReactNode;onManage:(id:number)=>void;onEdit:(id:number)=>void;onMetadata:(id:number)=>void;onUpdate:(id:number)=>void;onRemove:(id:number)=>void}){
  const [search,setSearch]=useState(''),[tag,setTag]=useState(''),[location,setLocation]=useState('');
  const knownTags=new Map<string,string>(),knownLocations=new Map<string,string>();
  for(const s of servers){for(const t of s.tags)if(!knownTags.has(t.toLowerCase()))knownTags.set(t.toLowerCase(),t);if(s.location&&!knownLocations.has('place:'+s.location.toLowerCase()))knownLocations.set('place:'+s.location.toLowerCase(),s.location);}
  const sorted=(values:Map<string,string>)=>[...values].sort((a,b)=>a[1].localeCompare(b[1],'de'));
  const needle=search.trim().toLowerCase(),filtered=servers.filter(s=>(!tag||s.tags.some(t=>t.toLowerCase()===tag))&&(!location||(location==='__none__'?!s.location:'place:'+s.location.toLowerCase()===location))&&(!needle||[s.name,s.agent_url,s.profile,s.location,s.infrastructure_name,...s.tags].join(' ').toLowerCase().includes(needle)));
  const active=!!(search||tag||location);
  function reset(){setSearch('');setTag('');setLocation('');}
  return <><div className="toolbar server-filters"><div className="search"><Search size={16}/><input aria-label="Server durchsuchen" placeholder="Name, Adresse, Tag oder Standort suchen …" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Server nach Tag filtern" value={tag} onChange={e=>setTag(e.target.value)}><option value="">Alle Tags</option>{tag&&!knownTags.has(tag)&&<option value={tag}>{tag}</option>}{sorted(knownTags).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Server nach Standort filtern" value={location} onChange={e=>setLocation(e.target.value)}><option value="">Alle Standorte</option><option value="__none__">Ohne Standort</option>{location&&location!=='__none__'&&!knownLocations.has(location)&&<option value={location}>{location.replace(/^place:/,'')}</option>}{sorted(knownLocations).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{active&&<button className="text-button" onClick={reset}><X size={14}/>Filter zurücksetzen</button>}<span>{filtered.length} von {servers.length} Servern</span></div>
  {filtered.length?<div className="server-cards">{filtered.map(s=><section className="panel server-card" key={s.id}><div className="server-card-top"><span className="tile-icon"><Server size={23}/></span>{status(s)}</div><h2>{s.name}</h2><p className="mono">{s.agent_url}</p><div className="server-tags"><span className="badge neutral">{s.kind==='docker'?'Docker':'Nativ'}</span><span className="badge neutral">{s.profile}</span></div><ClassificationBadges tags={s.tags} location={s.location} infrastructure_name={s.infrastructure_name}/>{isAdmin&&<button className="text-button classification-edit" aria-label={'Zuordnung für '+s.name+' bearbeiten'} onClick={()=>onMetadata(s.id)}><Tags size={13}/>Zuordnung bearbeiten</button>}{s.notes&&<p>{s.notes}</p>}<div className="server-values"><div><span>Verbindungen</span><strong>{fmt(s.stats?.sessions)}</strong></div><div><span>Anfragen/s</span><strong>{fmt(s.stats?.request_rate)}</strong></div></div><div className="server-card-actions"><button className="button secondary" onClick={()=>onManage(s.id)}>Verwalten<ArrowRight size={15}/></button>{isAdmin&&<><button className="icon-button" aria-label={'Agent auf '+s.name+' aktualisieren'} title="Agent aktualisieren" disabled={busy} onClick={()=>onUpdate(s.id)}><Download size={17}/></button><button className="icon-button" aria-label={'Server '+s.name+' bearbeiten'} onClick={()=>onEdit(s.id)}><Settings2 size={17}/></button><button className="icon-button red-text" aria-label={'Server '+s.name+' entfernen'} onClick={()=>onRemove(s.id)}><Trash2 size={17}/></button></>}</div></section>)}</div>:<section className="panel"><div className="empty"><Search size={28}/><h3>Keine passenden Server</h3><p>Ändere die Suche oder die Filter, um weitere Server zu sehen.</p><button className="button secondary" onClick={reset}>Filter zurücksetzen</button></div></section>}</>;
}
